language: generic
sudo: required
dist: trusty
services:
- docker
before_install: docker pull docker.io/alukiano/mr-builder
install:
- git reset --hard
script:
- make generate
- make kubevirtci-download
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make generate`. Please run it and commit the changes"; git status --porcelain;
  false; fi
- make bazel-tests
deploy:
- provider: script
  script: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}" && CONTAINER_PREFIX=index.docker.io/kubevirt
    CONTAINER_TAG=latest make bazel-push-images
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}" && CONTAINER_PREFIX=index.docker.io/kubevirt
    CONTAINER_TAG=$TRAVIS_BRANCH make bazel-push-images
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release.*$
- provider: script
  script: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}" && CONTAINER_PREFIX=index.docker.io/kubevirt
    CONTAINER_TAG=$TRAVIS_TAG make bazel-push-images
  skip_cleanup: true
  on:
    tags: true
- provider: script
  script: CONTAINER_PREFIX=index.docker.io/kubevirt CONTAINER_TAG=$TRAVIS_TAG make generate
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: mLIWMDQpFkBPCvPMbMGDLywB5tFyWAFUsbJudITSlGSioTXo1BYAHDq7chrgIVObgbxAZG+5YNtwx/6/InLRd6eikf1ZGwN2YTpYAxreTNRhC03RdSWblS0lJxPZUzM1BiSmrrhAMu5LKES1RTjPEjRy7ID82eVnazaT/jMZWzAVk3cNcxcrWx5NxkurxLEci8vL03n5ntxhhf9Jmw89Gp5RK5dsTks+fnTxGr/MtkJARBuo071sRirqV/PBb9zZP6M9plVY/Iv4cw2KhI1B1ISn4aXgCgkBRnaVmxfCMi2FyQs4FrUUJmCDyYLNmY50pnTEz+uF4ufI0We5sx+rmPh0Mr07NgyBKSJE8djjLMh6aE4XUL9oWBkRlNsGchKk7wfklUBMlS66mmZqZp3hLKBBn7fPgFMKlNWC+zhIrzGoLGFIlLj4Fp6D1WY6hIdWDAjQf48saCl6vqFgA0GQCHtGOqMsdT5yPo36Iuk7nP01CK0PeFWgcP5NMeZ1ZmmoHeauo2UaM/dRQyGN9XpNhqoikWwRqx52gn9OsoJok3JEEOvgs70fe8hF/R2hdJ9rPyGhloWDT8KML/EWJ4vBYEwZwQoEruxRJs7t36lveBtGUFuJdlY4gtzQTvYMKHWLPc4AknQ9zV4Amr31jP9nQ5TugwU8iQnxZM8s9AI7AFk=
  file:
    - _out/manifests/release/machine-remediation.$TRAVIS_TAG.yaml
  prerelease: true
  overwrite: true
  name: "$TRAVIS_TAG"
  on:
    repo: kubevirt/machine-remediation
    tags: true
env:
  global:
  - secure: fzd4YkojXC9TrUQlYWb/bAgHYByIB5IEJaCwA9qTfGwBky8lcLUNv2pwnRSs6i9LPVe9XIxIZrlG+6kKUlnG7J+quNqSQsMQcq9Qx6uS+cRUMq1RreF3xfWHk2AJjheiQeD3+vKxgohlfcQHbvgDFeoIguISWMNEygV9ZUvX5S+cltcmrTxEyd1XTBazBjrwooam2aNmUgS2CoVt4+ByXFSR5vHZ77CMX8Q6ECp/Ke+l2vOBe04JpBwl78Y349ZRvbIhwTlPOvQcg0spZQCg3cmN6B1U5ptQw/fWPLX0r70oxyLm4fP6siNeEDZLB1Nw+7K22nQK8Ck9kz3nvfymz60ha1hEFeXRqYFM3ZH8GiV34VUtVCY+CaTSlvKO7KJ5zUAhC9i5c/skZH0hYIPeGyk6CWb9dOrf3N+ej0ZcOw4699OzNp07UEZeyUU26+NySiLQGxg5bpbxA5sycfKwIfneQHvxaNztNayxtacmTlGsgICooqniS83EVd6ZJ4eQYefmQkD38CFbt/tjSOhy6idc3i5pabmiQZ9dyn3iHH0oySYgqdF86dch+Uej7XUaL5Wkw2W2YAs8bjuL+aBju/6f7xYq03Dy7YUjIwf3hYxTxwFKTTlkoQnibdDqyVrCto4s4AgnUD/QekgURMBzPJkqKYLCs6akeltyh0Us39Y=
  - secure: LqE74kFjwIqWEIxT2I775OWjig5isPtWcA4SSZ+NH/hFofJzcqZysYkIpaNo9KXB0wiTulHcpU5p1Ay1soEP0O2qsU0pYvC398O7GjC1Iwp5DNbfir+YzjYiIcpBAzt/KsKo1ZMLYdYfuIj7/p639BZV5CxPnTlm9I0f/Quov6QW/d9AOuAflB4NuSfX8JC1FUVdU+m5XQvj39IGqim39Xf70BQ8rPNfWaPQiNZsu1+WLoUHURJb+1H+lTxLPISCOb5r4n3qvd2xNMkuhaQ2hQEQB3yNM8+RiZaWQj7ckioUR3XsKFOzvaNYLnDqahYPu9B5z5er2j1QdRtDyd8bbz5CSuNvLxriHPvU2lv2IBYVsuD9A6ym6a3lvVR9V5gDWLbE6s9/BN808qEmTR4eRLos2SOvAbmSJr7N+OTwdZxB5+0nNUcLcnnpjzcyhgfsu9lsf49JGD3kpAohZqfE/OzyJ3ALf2TNgD8Ph5u35JGgwrsp220SW56n6bei2uX0pBWTjBCKfFtZwF4kxeLcv7TxiXPu3t1W3S5uqeMcXlTVqLdLrPA+wQ+TetY9Jsu/iNmELN+VZNpp2q8c2I4regimQQ4GKmSOL6cQeYaZaTeeq/ZjkwgJfaJVaA3bWwZdrHy9AV4FQFsgY5Tt74ZKupWDxAEKBd4SpHuxt1KdHxM=
