language: generic
sudo: required
dist: trusty
services:
- docker
before_install: docker pull alukiano/builder:28
install:
- git reset --hard
script:
- make bazel-generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make bazel-generate`. Please run it and commit the changes"; git status --porcelain;
  false; fi
- CONTAINER_TAG=$TRAVIS_TAG make bazel-generate-manifests-release
- make bazel-tests
deploy:
- provider: script
  script: hack/dockerized "docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}" &&
    CONTAINER_TAG=latest make bazel-push-images-release
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: hack/dockerized "docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}" &&
    CONTAINER_TAG=$TRAVIS_TAG make bazel-push-images-release
  skip_cleanup: true
  file: 
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: K7XQrKIr8sX/fKM3Zy38FyTuxFWL9cbi7dBV543sJ1Ls4rFoLANXszG/Sd/ZPlhms6XHEnqgnyn/2ALko4qkrySx6gPcguSKJZJSen93lQtUkUslvEcziFBpUri+QV9stdSRKV//mpB6qHkO1VpGWhQQLm9bfwB7Iy6rHiDG72asKaVJvLehYDb39NAGjTMYOL9xcVWC8HGhToMfyG9mLfuDgt/whB+GvcAnQIjFRIHMoSSKCYDGpvRlUeCgtVAf8LuXeIRFxnMcj6E68yyU3f/uoyVACdUrU0XjhyAdN4dDEeRNfo/15l9Na61dlWqv46UvXX+1Fm+ZkDqzpgpzuqk4xCyzi4MTc9btQuwfSJQOl9QGM5LlY0eCrkVusFLBB0/igJ/+JQbppkuxVa9xNuxgYWSLHYznPTdBcJZKZinU4LQzxhIyhe6PIRiTqKg6kr0U2u8R4Rwt6zNvBS+Ka4jvm7cC/c3aznF6lvhlwvj6/1elWUZILM7HRxw3itpx1iXPfFa1JlQToNTeWPtZoIjQT7qpZYen7otcsKRu9BOV6bdwjBmIwALROF1FHrk8wma1ZZwv2fHAYsmEgOTFqHYYp4huzyXecFih+d639XfZEHJpOb7CA+9PlbJzGjZNZj5u2vztneqQOwQtyz9B/ig4HiHyH4AiuDGUTZewUFc=
  file: _out/manifests/noderecovery.yaml
  prerelease: true
  overwrite: true
  name: "$TRAVIS_TAG"
  on:
    repo: kubevirt/node-recovery
    tags: true
env:
  global:
  - secure: GsDKM4cU9T1UAUZYWweQninvn+x7SV3j9kKXSMq4D8ULkXACp/G1MO7q86U7Eyc7+WmI/f5UYao8Smn4LcqpL7jC1CP94sjticAcn5HbCQPoA2yitgChtUsWQfYBZSOUSqmnRscQLb/LNAO0u32riEfT0Yx3AIyFUUf4DmVl7B6duOJCEg2gy3jKM39GCWVJqsu7yiiyW+FOaTJNqposLJlJQz5KPRJXWtqH2YY+wVzsZArtI7Ip46EqP/7J0G8oV4+fDl614yBFkCqR3a58+fSnrNyTSGbdVR94nkQzHqAAgPSdiK3cpMZ8I0eVITQcKKo3ko4o5h9cstW9mG22qaniaUodVaIueN9yxq6Tz6g8aM4s0EFu2JkIX92C5vUUts+NChLPi5OrAySVHcIlcwtH2DxDQ2FamFWhTnDgJtiIMND6HbX4KjWqdWYrQPUS3l+MZblEJ57MX1+qzR7auZsqCT0Y3LWuiqQ1451ivYBBK8IbjVLAUJPmm3oPjOtS+9bjs41jO7u3MkVgGvx88SMhaZ51IaSdqDhztNZ9zdBaZ0zwiUUjC3sk2PAQGdxvEoybdZ4Zf+d41X5OyKwNRtb0AeI0nAd9m24M6r2R/KujouEpZ+eMOv/Kn9tmKBoSI30/IbgnM3kE2rdlAXN9fUigHOfqhGGWUhiewJzpdlw=
  - secure: Zv1R6LzxCe587UOnl6dvii9NdBWsIzsUuu2dGI3xeWzGIrV00MoDDNMjUq/wlYCjUrBgUw+cNBnhyUA3YGqs+p7tuKU3HRz849wNPhFmo5rF9toIrun5PBAXGjrGDMDM30OuBdjF/2qfKwEQr8NBfvjfbu9O8wJdBf0nhe84F0rsmLM0+slcO+gh6UfXS7VVZKe8rERqiUwG75tTeVdLJsEn33BUhdThHX2ILPWHgVM9hh78b4EK2WRBQ2NcVmoTIrXPffHBXCM5r/7ssSZYmTdtUmQIIjMAcxev3eO17cvlDyG5MXFZtS2FDB2e9gfwspQadDtDpIhZ+509rcfjRED6MmdJh62ZUxd4PBqTp1323hCtSYVYQF0I4+RlaOHTnChk4pDJm5dvl/KRNFeTLy5YnocsEUkbDMe3lcfogoR5IzFYOhe6wWlgruebM5340QdxJp0iLDai0q00p+lXJVLphVxKuhafvHf4dx89rOxY6AbXPOSNcFJ6Oc/mYgMzgY1Ots79s/2VuhSIqP19tKnKbqPBn2UL6hZlgDTkGvpXD/CMmjHA2bXuRj838d86AybdNMa1MACeinRi5s+PSko1+bpsMYG6JLFf7d1I6vDtpkuFycxyZvK5rCpp40g142QpbyUHAE9j2PYTEwOgFjdn5CbOlukJefRGls9UVpE=
