language: generic
sudo: required
dist: trusty
services:
- docker
before_install: docker pull docker.io/alukiano/mro-builder
install:
- git reset --hard
script:
- make generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make generate`. Please run it and commit the changes"; git status --porcelain;
  false; fi
- make bazel-tests
deploy:
- provider: script
  script: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}" && CONTAINER_PREFIX=index.docker.io/kubevirt
    CONTAINER_TAG=latest make bazel-push-images
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}" && CONTAINER_PREFIX=index.docker.io/kubevirt
    CONTAINER_TAG=$TRAVIS_TAG make bazel-push-images
  skip_cleanup: true
  file: 
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: "OELAdPWwhl2tn0r77t6ZH9uLMXuffRgV1StzroiEdQ9JAPR7s7q7WE+egu7mvX/hyeILd875fosj7b4pTiVsd2nEVEExDlhOdWnICiOZJ45rNvuYRKNz6HNgtahyzJTASTDcvAXBs9jGxOXDWZxklvjtniwQ7jxaOBJMQo5xu4qOBX8aRnvSipapKcDW5O1pilxcq8jFDwfWZQOOPNDUoVu+8IKn5l0ZhmWLP/1YLuicS4jysK/ol0EUmwQlQU2Mr2Jx2WVNsm/C0l9BdNABVHaVnte9crxYxZ5a99vVnXwBjZXtaUNgWi68nmrZwHbvA0bq2BUlV1B3uX+p2ACx00dbNJAgqFPD0Z+MfnhKLZf6+g/sLZN3m7yBWwd+9jrcuBEfrhG/Ol7zdAh1IoXFmdpuyilfNYtLjsu4eOX4CeA+HvyTlhjhcegWwKm3epyZkJ4X21Nk3j5k56KFuiIul8oSDuCNB/ZyD0jJ3rv0Rl5yLU/xrbE9U9qiQS8UPdg94cCvnW24R4u1zeanZsSE+9g5VB1KPjeLY1p/0274VD2CLigk7bt3FWsZoAzPQmncY+58Qls9FBQp8FL3wh7snhVfebYIRkdBZs2DyJDTsJrQCKwk/+8u5kve+iAjmVfoR11FTgJ0gYyGvKK6/hm37yb5CuK+7/j2+1jfVHzOkT0="
  file: _out/manifests/release/machine-remediation-operator.yaml
  prerelease: true
  overwrite: true
  name: "$TRAVIS_TAG"
  on:
    repo: kubevirt/machine-remediation-operator
    tags: true
env:
  global:
  - secure: fzd4YkojXC9TrUQlYWb/bAgHYByIB5IEJaCwA9qTfGwBky8lcLUNv2pwnRSs6i9LPVe9XIxIZrlG+6kKUlnG7J+quNqSQsMQcq9Qx6uS+cRUMq1RreF3xfWHk2AJjheiQeD3+vKxgohlfcQHbvgDFeoIguISWMNEygV9ZUvX5S+cltcmrTxEyd1XTBazBjrwooam2aNmUgS2CoVt4+ByXFSR5vHZ77CMX8Q6ECp/Ke+l2vOBe04JpBwl78Y349ZRvbIhwTlPOvQcg0spZQCg3cmN6B1U5ptQw/fWPLX0r70oxyLm4fP6siNeEDZLB1Nw+7K22nQK8Ck9kz3nvfymz60ha1hEFeXRqYFM3ZH8GiV34VUtVCY+CaTSlvKO7KJ5zUAhC9i5c/skZH0hYIPeGyk6CWb9dOrf3N+ej0ZcOw4699OzNp07UEZeyUU26+NySiLQGxg5bpbxA5sycfKwIfneQHvxaNztNayxtacmTlGsgICooqniS83EVd6ZJ4eQYefmQkD38CFbt/tjSOhy6idc3i5pabmiQZ9dyn3iHH0oySYgqdF86dch+Uej7XUaL5Wkw2W2YAs8bjuL+aBju/6f7xYq03Dy7YUjIwf3hYxTxwFKTTlkoQnibdDqyVrCto4s4AgnUD/QekgURMBzPJkqKYLCs6akeltyh0Us39Y=
  - secure: LqE74kFjwIqWEIxT2I775OWjig5isPtWcA4SSZ+NH/hFofJzcqZysYkIpaNo9KXB0wiTulHcpU5p1Ay1soEP0O2qsU0pYvC398O7GjC1Iwp5DNbfir+YzjYiIcpBAzt/KsKo1ZMLYdYfuIj7/p639BZV5CxPnTlm9I0f/Quov6QW/d9AOuAflB4NuSfX8JC1FUVdU+m5XQvj39IGqim39Xf70BQ8rPNfWaPQiNZsu1+WLoUHURJb+1H+lTxLPISCOb5r4n3qvd2xNMkuhaQ2hQEQB3yNM8+RiZaWQj7ckioUR3XsKFOzvaNYLnDqahYPu9B5z5er2j1QdRtDyd8bbz5CSuNvLxriHPvU2lv2IBYVsuD9A6ym6a3lvVR9V5gDWLbE6s9/BN808qEmTR4eRLos2SOvAbmSJr7N+OTwdZxB5+0nNUcLcnnpjzcyhgfsu9lsf49JGD3kpAohZqfE/OzyJ3ALf2TNgD8Ph5u35JGgwrsp220SW56n6bei2uX0pBWTjBCKfFtZwF4kxeLcv7TxiXPu3t1W3S5uqeMcXlTVqLdLrPA+wQ+TetY9Jsu/iNmELN+VZNpp2q8c2I4regimQQ4GKmSOL6cQeYaZaTeeq/ZjkwgJfaJVaA3bWwZdrHy9AV4FQFsgY5Tt74ZKupWDxAEKBd4SpHuxt1KdHxM=
