---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: node01
  namespace: noderecovery
  labels:
    set: master
    kubevirt.io: noderecovery
spec:
  providerConfig:
    value:
      apiVersion: "externalproviderconfig/v1alpha1"
      kind: "ExtMachineProviderConfig"
      roles:
      - Master
      crudPrimitives:
        name: inline
        container:
          name: baremetal-fencing
          image: quay.io/beekhof/fence-agents:0.0.2
        checkCmd:  [ "/bin/fence_lockfile", "-x", "--lockdir", "/mnt", "-o", "status" ]
        createCmd: [ "/bin/fence_lockfile", "-x", "--lockdir", "/mnt", "-o", "on"  ]
        deleteCmd: [ "/bin/fence_lockfile", "-x", "--lockdir", "/mnt", "-o", "off" ]
        argumentFormat: cli
        passTargetAs: target
---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: node02
  namespace: noderecovery
  labels:
    set: node
    kubevirt.io: noderecovery
spec:
  providerConfig:
    value:
      apiVersion: "externalproviderconfig/v1alpha1"
      kind: "ExtMachineProviderConfig"
      roles:
      - Node
      crudPrimitives:
        name: inline
        container:
          name: baremetal-fencing
          image: quay.io/beekhof/fence-agents:0.0.2
        checkCmd:  [ "/bin/fence_lockfile", "-x", "--lockdir", "/mnt", "-o", "status" ]
        createCmd: [ "/bin/fence_lockfile", "-x", "--lockdir", "/mnt", "-o", "on"  ]
        deleteCmd: [ "/bin/fence_lockfile", "-x", "--lockdir", "/mnt", "-o", "off" ]
        argumentFormat: cli
        passTargetAs: target
