---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: noderecovery
  labels:
    kubevirt.io: "noderecovery"
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - update
      - create
      - patch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - list
      - watch
      - get
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - list
      - watch
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: noderecovery
  namespace: kube-system
  labels:
    kubevirt.io: "noderecovery"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: noderecovery
  labels:
    kubevirt.io: "noderecovery"
roleRef:
  kind: ClusterRole
  name: noderecovery
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: noderecovery
    namespace: kube-system
