apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machineremediations.machineremediation.kubevirt.io
spec:
  group: machineremediation.kubevirt.io
  names:
    kind: MachineRemediation
    plural: machineremediations
    shortNames:
    - mr
    - mrs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of MachineRemediation
          properties:
            machineName:
              description: MachineName contains the name of machine that should be
                remediate
              type: string
            type:
              description: Type contains the type of the remediation
              type: string
          type: object
        status:
          description: Most recently observed status of MachineRemediation resource
          properties:
            endTime:
              format: date-time
              type: string
            reason:
              type: string
            startTime:
              format: date-time
              type: string
            state:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
