apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: machinehealthchecks.machineremediation.openshift.io
spec:
  group: machineremediation.openshift.io
  names:
    kind: MachineHealthCheck
    plural: machinehealthchecks
    shortNames:
    - mhc
    - mhcs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: Specification of machine health check policy
          properties:
            remediationStrategy:
              description: RemediationStrategy to use in case of problem detection
                default is machine deletion
              type: string
            selector:
              description: Label selector to match machines whose health will be exercised
              type: object
          required:
          - selector
          type: object
        status:
          description: Most recently observed status of MachineHealthCheck resource
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
